//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.WpfClient.TitleServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TitleServiceReference.ITitleService")]
    public interface ITitleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/InsertTitle", ReplyAction="http://tempuri.org/ITitleService/InsertTitleResponse")]
        bool InsertTitle(FinalProject.Domain.Title title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/InsertTitle", ReplyAction="http://tempuri.org/ITitleService/InsertTitleResponse")]
        System.Threading.Tasks.Task<bool> InsertTitleAsync(FinalProject.Domain.Title title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/GetTitleById", ReplyAction="http://tempuri.org/ITitleService/GetTitleByIdResponse")]
        FinalProject.Domain.Title GetTitleById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/GetTitleById", ReplyAction="http://tempuri.org/ITitleService/GetTitleByIdResponse")]
        System.Threading.Tasks.Task<FinalProject.Domain.Title> GetTitleByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/GetTitlesByTitle", ReplyAction="http://tempuri.org/ITitleService/GetTitlesByTitleResponse")]
        FinalProject.Domain.Title[] GetTitlesByTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/GetTitlesByTitle", ReplyAction="http://tempuri.org/ITitleService/GetTitlesByTitleResponse")]
        System.Threading.Tasks.Task<FinalProject.Domain.Title[]> GetTitlesByTitleAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/GetTitleRangeByTitle", ReplyAction="http://tempuri.org/ITitleService/GetTitleRangeByTitleResponse")]
        FinalProject.Domain.Title[] GetTitleRangeByTitle(string title, int startIndex, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/GetTitleRangeByTitle", ReplyAction="http://tempuri.org/ITitleService/GetTitleRangeByTitleResponse")]
        System.Threading.Tasks.Task<FinalProject.Domain.Title[]> GetTitleRangeByTitleAsync(string title, int startIndex, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/GetTitleCountByTitle", ReplyAction="http://tempuri.org/ITitleService/GetTitleCountByTitleResponse")]
        int GetTitleCountByTitle(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/GetTitleCountByTitle", ReplyAction="http://tempuri.org/ITitleService/GetTitleCountByTitleResponse")]
        System.Threading.Tasks.Task<int> GetTitleCountByTitleAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/UpdateTitle", ReplyAction="http://tempuri.org/ITitleService/UpdateTitleResponse")]
        bool UpdateTitle(FinalProject.Domain.Title title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/UpdateTitle", ReplyAction="http://tempuri.org/ITitleService/UpdateTitleResponse")]
        System.Threading.Tasks.Task<bool> UpdateTitleAsync(FinalProject.Domain.Title title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/DeleteTitle", ReplyAction="http://tempuri.org/ITitleService/DeleteTitleResponse")]
        bool DeleteTitle(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITitleService/DeleteTitle", ReplyAction="http://tempuri.org/ITitleService/DeleteTitleResponse")]
        System.Threading.Tasks.Task<bool> DeleteTitleAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITitleServiceChannel : FinalProject.WpfClient.TitleServiceReference.ITitleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TitleServiceClient : System.ServiceModel.ClientBase<FinalProject.WpfClient.TitleServiceReference.ITitleService>, FinalProject.WpfClient.TitleServiceReference.ITitleService {
        
        public TitleServiceClient() {
        }
        
        public TitleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TitleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TitleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TitleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertTitle(FinalProject.Domain.Title title) {
            return base.Channel.InsertTitle(title);
        }
        
        public System.Threading.Tasks.Task<bool> InsertTitleAsync(FinalProject.Domain.Title title) {
            return base.Channel.InsertTitleAsync(title);
        }
        
        public FinalProject.Domain.Title GetTitleById(string id) {
            return base.Channel.GetTitleById(id);
        }
        
        public System.Threading.Tasks.Task<FinalProject.Domain.Title> GetTitleByIdAsync(string id) {
            return base.Channel.GetTitleByIdAsync(id);
        }
        
        public FinalProject.Domain.Title[] GetTitlesByTitle(string title) {
            return base.Channel.GetTitlesByTitle(title);
        }
        
        public System.Threading.Tasks.Task<FinalProject.Domain.Title[]> GetTitlesByTitleAsync(string title) {
            return base.Channel.GetTitlesByTitleAsync(title);
        }
        
        public FinalProject.Domain.Title[] GetTitleRangeByTitle(string title, int startIndex, int count) {
            return base.Channel.GetTitleRangeByTitle(title, startIndex, count);
        }
        
        public System.Threading.Tasks.Task<FinalProject.Domain.Title[]> GetTitleRangeByTitleAsync(string title, int startIndex, int count) {
            return base.Channel.GetTitleRangeByTitleAsync(title, startIndex, count);
        }
        
        public int GetTitleCountByTitle(string id) {
            return base.Channel.GetTitleCountByTitle(id);
        }
        
        public System.Threading.Tasks.Task<int> GetTitleCountByTitleAsync(string id) {
            return base.Channel.GetTitleCountByTitleAsync(id);
        }
        
        public bool UpdateTitle(FinalProject.Domain.Title title) {
            return base.Channel.UpdateTitle(title);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateTitleAsync(FinalProject.Domain.Title title) {
            return base.Channel.UpdateTitleAsync(title);
        }
        
        public bool DeleteTitle(string id) {
            return base.Channel.DeleteTitle(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTitleAsync(string id) {
            return base.Channel.DeleteTitleAsync(id);
        }
    }
}
