// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using FinalProject.Data;

namespace FinalProject.Data.Migrations
{
    [DbContext(typeof(IMDbContext))]
    [Migration("20190324184518_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Data.Title", b =>
                {
                    b.Property<string>("TitleId")
                        .HasColumnName("titleId")
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.Property<short?>("EndYear")
                        .HasColumnName("endYear");

                    b.Property<string>("Genres")
                        .HasColumnName("genres")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsAdult")
                        .HasColumnName("isAdult");

                    b.Property<string>("OriginalTitle")
                        .HasColumnName("originalTitle")
                        .HasMaxLength(1000);

                    b.Property<string>("PrimaryTitle")
                        .HasColumnName("primaryTitle")
                        .HasMaxLength(1000);

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnName("runtimeMinutes");

                    b.Property<short?>("StartYear")
                        .HasColumnName("startYear");

                    b.Property<string>("TitleType")
                        .HasColumnName("titleType")
                        .HasMaxLength(20);

                    b.HasKey("TitleId");

                    b.ToTable("titles","movie");
                });
#pragma warning restore 612, 618
        }
    }
}
